- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_userprofiles/version.py
- setup.py
> release: v1.0.0a1

- invenio_userprofiles/version.py
> version: post-release bump

- .travis.yml
* Adds section for automatizing PyPI releases.  (closes #5)
> travis: addition of deploy section

- setup.py
> i18n: entry point module name fix

- invenio_userprofiles/api.py
- invenio_userprofiles/ext.py
- invenio_userprofiles/forms.py
- invenio_userprofiles/models.py
- invenio_userprofiles/views.py
- setup.py
- tests/test_api.py
> views: settings menu fix + flask-security fix

- invenio_userprofiles/api.py
- invenio_userprofiles/ext.py
- invenio_userprofiles/forms.py
- invenio_userprofiles/models.py
- invenio_userprofiles/views.py
- setup.py
- tests/test_api.py
> views: userprofile template filter

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_userprofiles/version.py
> release: v1.0.0a2

- examples/app.py
* Updates documentation of accounts cli usage.
(addresses inveniosoftware/invenio-accounts#90)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> global: update of example documentation

- invenio_userprofiles/ext.py
- invenio_userprofiles/forms.py
- invenio_userprofiles/models.py
- invenio_userprofiles/templates/invenio_userprofiles/register_user.html
- tests/conftest.py
- tests/test_api.py
- tests/test_models.py
- tests/test_views.py
* Optionally adds UserProfile form fields to registeration form.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
> views: profile details in registeration form

- .editorconfig
- .gitignore
- .travis.yml
- MANIFEST.in
- examples/app.py
- invenio_userprofiles/admin.py
- setup.py
- tests/test_admin.py
- tests/test_invenio_userprofile.py
- tests/test_views.py
* Adds admin views for managing additional information about users.
Reviewed-by: Jiri Kuncar <jiri.kuncar@cern.ch>
Signed-off-by: Bruno Cuc <bruno.cuc@cern.ch>
--
closes #12
> global: admin views for invenio-userprofiles

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_userprofiles/version.py
> release: v1.0.0a3

- invenio_userprofiles/forms.py
- tests/test_views.py
* Fixes bug where an anonymous user trying to register an account with
an existing username would thrown an exception.
* Adds validation error message to username validation.
> forms: existing user validation fix

- invenio_userprofiles/templates/invenio_userprofiles/settings/profile.html
- invenio_userprofiles/views.py
- setup.py
> views: breadcrumbs fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_userprofiles/version.py
> release: v1.0.0a4

- examples/app.py
- invenio_userprofiles/ext.py
- invenio_userprofiles/models.py
- invenio_userprofiles/views.py
- setup.py
- tests/conftest.py
- tests/test_views.py
* Fixes initialization order fix which happened if Invenio-Accounts was
installed prior to UserProfiles.
> global: initialization order fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_userprofiles/version.py
> release: v1.0.0a5

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_userprofiles/version.py
> release: v1.0.0a7

- examples/app.py
- setup.py
- tests/conftest.py
- tests/test_invenio_userprofile.py
> installation: Flask>=0.11

- .tx/config
- invenio_userprofiles/translations/es/LC_MESSAGES/messages.po
- invenio_userprofiles/translations/fr/LC_MESSAGES/messages.po
- invenio_userprofiles/translations/it/LC_MESSAGES/messages.po
Signed-off-by: Alizee Pace <alizee.pace@gmail.com>
> i18n: tx configuration fix

- docs/api.rst
- docs/conf.py
- invenio_userprofiles/api.py
- invenio_userprofiles/config.py
- invenio_userprofiles/ext.py
- invenio_userprofiles/forms.py
- invenio_userprofiles/models.py
- invenio_userprofiles/validators.py
- invenio_userprofiles/views.py
* Improves documentation. (addresses #48)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> docs: addition of param and result sections

- MANIFEST.in
- examples/app-fixtures.sh
- examples/app-setup.sh
- examples/app-teardown.sh
- examples/app.py
- tests/test_examples_app.py
* Adds test_examples_app.py. (closes #55)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> tests: addition of test_examples_app.py

- docs/requirements.txt
> docs: requirements for ReadTheDocs

- MANIFEST.in
- invenio_userprofiles/models.py
- tests/test_models.py
* FIX Fixes a bug in user's initialization in models.
Signed-off-by: PaulinaLach paulina.malgorzata.lach@cern.ch
> global: profile creation fix

- examples/app-setup.sh
- examples/app-teardown.sh
- examples/app.py
- invenio_userprofiles/alembic/71634726ec7e_create_userprofiles_branch.py
- invenio_userprofiles/alembic/c25ef2c50ffa_create_userprofiles_tables.py
- setup.py
- tests/conftest.py
- tests/test_invenio_userprofile.py
> global: initial alembic recipes

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_userprofiles/version.py
> release: v1.0.0a9

- .editorconfig
- .gitignore
- .travis.yml
- CONTRIBUTING.rst
- INSTALL.rst
- MANIFEST.in
- README.rst
- docs/Makefile
- docs/conf.py
- docs/configuration.rst
- docs/examplesapp.rst
- docs/make.bat
- invenio_userprofiles/config.py
- invenio_userprofiles/models.py
- invenio_userprofiles/version.py
- pytest.ini
- requirements-devel.txt
- run-tests.sh
- setup.py
- tests/test_examples_app.py
* FIX Adds changes according to release preparation checklist.
Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>
> global: release checklist

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_userprofiles/version.py
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
> release: 1.0.0.a10

- docs/examplesapp.rst
- examples/app.py
- invenio_userprofiles/alembic/71634726ec7e_create_userprofiles_branch.py
- invenio_userprofiles/alembic/c25ef2c50ffa_create_userprofiles_tables.py
- invenio_userprofiles/models.py
- tests/test_invenio_userprofile.py
* fix example app rendering problems on readthedocs. (closes #78)
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
> docs: fix example app rendering problems on readthedocs

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_userprofiles/version.py
> release: v1.0.0b1

- examples/app-fixtures.sh
- examples/app.py
- examples/requirements.txt
* Fixes access to admin page. (closes #81)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> examples: fix access to admin page

- CHANGES.rst
- RELEASE-NOTES.rst
- docs/conf.py
- invenio_userprofiles/forms.py
- invenio_userprofiles/version.py
- pytest.ini
- run-tests.sh
- tests/conftest.py
- tests/test_forms.py
Linked to: https://github.com/inveniosoftware/invenio-oauthclient/pull/155
> global: disable CSRF token for inner forms

- tests/test_admin.py
Closes https://github.com/inveniosoftware/invenio-userprofiles/issues/89
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>
> tests: fix flask_admin import

- examples/app-setup.sh
- tests/test_examples_app.py
* add webpack build
* (closes #92 )
> examples: fix setup script

- setup.py
> setup: pins pytest & Werkzeug versions

- .travis.yml
- CHANGES.rst
- examples/app-setup.sh
- invenio_userprofiles/version.py
- requirements-devel.txt
- setup.py
* drop support for python 2.7
* update python dependencies
* closes #96
> Centrally manage flask version through invenio-base

- CHANGES.rst
- invenio_userprofiles/version.py
- setup.py
~~requires #101~~
- closes #99 
- closes #100
> release:  v1.1.1

- invenio_userprofiles/templates/semantic-ui/invenio_userprofiles/settings/profile.html
> profile: set cancel button color

- CHANGES.rst
- invenio_userprofiles/version.py
- setup.py
> release: v1.2.0a3

- invenio_userprofiles/views.py
- setup.cfg
- requires https://github.com/inveniosoftware/invenio-accounts/pull/406
- requires https://github.com/inveniosoftware/flask-security-invenio/pull/47
- requires https://github.com/inveniosoftware/invenio-userprofiles/pull/135
- closes https://github.com/inveniosoftware/invenio-communities/issues/536
If this change is approved, we might want to revert https://github.com/inveniosoftware/pytest-invenio/pull/75 😢
> views: mark user as changed on update

- invenio_userprofiles/alembic/41157f1933d6_remove_table.py
closes #132 
Migrate data from `userprofiles_userprofile` table to `accounts_user` table.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder** …
> alembic: migrate data to invenio-accounts user table

- invenio_userprofiles/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
> i18n: add german translations

- CHANGES.rst
- invenio_userprofiles/__init__.py
- invenio_userprofiles/alembic/41157f1933d6_remove_table.py
fixes https://github.com/inveniosoftware/invenio-userprofiles/issues/141
> alembic: added migration dependency

- CHANGES.rst
- invenio_userprofiles/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …
> release: v2.0.5

- .github/workflows/i18n-pull.yml
- .github/workflows/i18n-push.yml
- .github/workflows/tests.yml
- run-i18n-tests.sh
- run-tests.sh
- setup.cfg
test: adds dry extract_messages command
> ci: adds i18n workflow

- invenio_userprofiles/forms.py
- invenio_userprofiles/views.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162
> translations: fix string format

- invenio_userprofiles/alembic/41157f1933d6_remove_table.py
- run-tests.sh
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …
> alembic: fix recipe based on latest sqlalchemy-continuum

- invenio_userprofiles/templates/invenio_userprofiles/settings/profile.html
- invenio_userprofiles/templates/semantic-ui/invenio_userprofiles/settings/profile.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2301
> settings profile: Update buttons with labeled styling and a11y fixes

- CHANGES.rst
- invenio_userprofiles/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …
> release: v2.3.0

- invenio_userprofiles/forms.py
- invenio_userprofiles/views.py
All tests pass locally but alembic
> email: use lowercase to compare

- .github/workflows/tests.yml
- CHANGES.rst
- invenio_userprofiles/__init__.py
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
> release: v3.1.0
